stages:
  - compile
  - package

variables:
  DEFAULT_IMAGE: eclipse-temurin:21-jdk-alpine
  MAJOR: "1"
  MINOR: "0"


compile:
  stage: compile
  image: $DEFAULT_IMAGE
  script:
    - ./gradlew compileJava
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

package:
  stage: package
  image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team15/archportal/archportalbackend/java-docker:latest
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - DATE=$(date +%Y%m%d)
    - VERSION="$MAJOR.$MINOR.$DATE-$CI_PIPELINE_ID"
    - IMAGE=$CI_REGISTRY_IMAGE/acl
    - echo "Building version $VERSION"
    - echo "$CI_REGISTRY_PASSWORD" | docker login registry.gitlab.com -u "$CI_REGISTRY_USER" --password-stdin

    - ./gradlew bootBuildImage --imageName=$IMAGE:$VERSION


    - docker tag $IMAGE:$VERSION $IMAGE:latest
    - docker push $IMAGE:$VERSION
    - docker push $IMAGE:latest
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
